version: '3'
services:

  mongo:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017

  arangodb:
    container_name: arangodb
    hostname: arangodb
    image: arangodb 
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1

  couchbase:
    container_name: couchbase
    hostname: couchbase
    image: couchbase
    restart: always
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210

  cassandra:
    container_name: cassandra
    hostname: cassandra
    image: cassandra
    restart: always
    ports:
      - 9042:9042

  postgres:
    container_name: postgres
    hostname: postgres
    image: mdillon/postgis
    restart: always
    ports:
      - 5432:5432

  # cassandra:
  #   container_name: apache-cassandra
  #   hostname: apache-cassandra
  #   image: cassandra
  #   restart: always
  #   environment:
  #   - CASSANDRA_START_RPC=true
  #   - CASSANDRA_SEEDS=cassandra0
  #   - CASSANDRA_CLUSTER_NAME=mtech_cluster
  #   ports:
  #     - 9042:9042
  #     - 9160:9160
  #     - 7199:7199
  #     - 8778:8778
  #   ulimits:
  #     memlock: -1
  #     nproc: 32768
  #     nofile: 100000