---
- name: Portainer | docker container start
  docker_container:
    name: portainer
    image: portainer/portainer
    state: started
    restart_policy: always
    ports:
      - '9000:9000'
    volumes: '/var/run/docker.sock:/var/run/docker.sock'

- name: Docker | Ensure user can use docker command without sudo
  user:
    name: '{{ docker_main_user }}'
    group: docker

- name: Start Docker Compose file with databases
  docker_service:
    project_src: /srv/vagrant-microservices/ansible/docker/databases


#Contains orders to download CouchBase and Install it using Pip

- name: Download LibCouchBase
  command: sudo wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-4-x86_64.rpm

- name: Allow permissions
  command: sudo rpm -iv couchbase-release-1.0-4-x86_64.rpm

- name: Install LibCouchBases
  command: sudo yum install libcouchbase-devel libcouchbase2-bin gcc gcc-c++ -y

- name: Install Python-dev
  command: sudo yum install gcc gcc-c++ python-devel python-pip -y

- name: Install Couchbase
  command: sudo pip install couchbase